### ISSUE TITLE
Shell-fm does not work with other mp3 streams (not last.fm)

### ISSUE THREAD

**Issue by dumghen** [jkramer/shell-fm#25]
Is this possible? To have playing with shell-fm other mp3/ogg streams?
I think this should not be so complicated.
Thanks!

**Comment by jkramer** [comment]
shell-fm is for Last.FM radio streams. If you want to play other streams, use another player. :) mplayer for example works great for all kinds of streams.

**Comment by dumghen** [comment]
Shell-fm is a very good player for OpenWRT distribution for wireless devices.
Sadly, the it does not recognize another mp3 streams...

One more question: could someone develop from existing shell-fm sources, one version that will support another mp3 streams (meaning is it difficult to adapt?)

Thanks!

**Comment by jkramer** [comment]
Last.FM radio streams are not like other radio streams. They consist of a XSPF playlist which has to be parsed to to obtain the URLs of the single track MP3s. This allows us to skip tracks, while other "normal" streams are just that - streams (that is, lots of tracks or random audio concatenated to one big file/stream). So using the shell-fm sources for building a player for generic MP3/Ogg streams doesn't make much sense, since you'd throw 99% of the features away and pretty much start from the beginning.

If you're looking for a lightweigt way to play streams on a WRT, try installing a simple and lightweight player like madplay for MP3 or ogg123 for Ogg Vorbis and use curl or wget to pipe the stream into it, e.g. curl -s $STREAM_URL | madplay -q -
