### ISSUE TITLE
shell-fm outputs ERROR: Failed to load plugin /usr/lib/ao/plugins-4/libesd.so => dlopen() failed before playing every song.

### ISSUE THREAD

**Issue by Daenyth** [jkramer/shell-fm#7]
I have no clue what this might be honestly. One of the users reported it. Original bug report [here](http://bugs.archlinux.org/task/19814).

**Comment by jkramer** [comment]
I don't think this is related to shell-fm, it looks more like a general problem with libao or its configuration. shell-fm doesn't load any plugins, it just uses the API of libao for playback. libao loads plugins transparently depending on its configuration. I don't see how this can be fixed in shell-fm. Please contact the developers of libao or the maintainer of the arch libao package instead.

**Comment by Daenyth** [comment]
Decent chance of pebkac I think. I certainly haven't seen any issue with it, nor has any one else that I know of...
